name: Debian package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker://docker.pkg.github.com/${{ github.actor }}/efalive_docker/efalive-development:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2
      - name: Build debian package
        run: |
          ./build_deb.sh
          echo "secrets.FTP_USER"
      - uses: actions/upload-artifact@v2
        with:
          name: efa2.deb
          path: efa2_2.2.2.48-1_all.deb
