name: Debian package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker://docker.pkg.github.com/${{ github.actor }}/efalive_docker/efalive-development:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2
      - name: Build debian package
        run: |
          ./build_deb.sh
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          /usr/bin/deploy_registry.sh efa2_2.2.2.48-1_all.deb efa2 buster ${{secret.FTP_USER}} ${{secret.FTP_SECRET}}
      - uses: actions/upload-artifact@v2
        with:
          name: efa2.deb
          path: efa2_2.2.2.48-1_all.deb
